version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: c_rabbitmq
    restart: always
    ports:
      # RabbitMQ ana iletişim portu (AMQP)
      - "5672:5672"
      # Web Yönetim Arayüzü portu (HTTP)
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq

volumes:
  rabbitmq_data:
  rabbitmq_logs:
